"""create_auth_tables

Revision ID: 41da306a6c97
Revises: 
Create Date: 2026-09-09 15:41:37.982024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41da306a6c97'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jurisdictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.Enum('VILLAGE', 'TALUKA', 'DISTRICT', 'STATE', 'NATIONAL', name='jurisdiction_type_enum'), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['jurisdictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jurisdictions_code'), 'jurisdictions', ['code'], unique=False)
    op.create_index(op.f('ix_jurisdictions_id'), 'jurisdictions', ['id'], unique=False)
    op.create_index(op.f('ix_jurisdictions_name'), 'jurisdictions', ['name'], unique=False)
    op.create_index(op.f('ix_jurisdictions_parent_id'), 'jurisdictions', ['parent_id'], unique=False)
    op.create_index(op.f('ix_jurisdictions_type'), 'jurisdictions', ['type'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('mobile_number', sa.String(length=20), nullable=True),
    sa.Column('emp_id', sa.String(length=50), nullable=True),
    sa.Column('org_id', sa.String(length=50), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_emp_id'), 'users', ['emp_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_mobile_number'), 'users', ['mobile_number'], unique=True)
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=True)
    op.create_table('user_role_jurisdictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('jurisdiction_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', 'jurisdiction_id', name='uq_user_role_jurisdiction')
    )
    op.create_index(op.f('ix_user_role_jurisdictions_id'), 'user_role_jurisdictions', ['id'], unique=False)
    op.create_index(op.f('ix_user_role_jurisdictions_jurisdiction_id'), 'user_role_jurisdictions', ['jurisdiction_id'], unique=False)
    op.create_index(op.f('ix_user_role_jurisdictions_role_id'), 'user_role_jurisdictions', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_role_jurisdictions_user_id'), 'user_role_jurisdictions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_role_jurisdictions_user_id'), table_name='user_role_jurisdictions')
    op.drop_index(op.f('ix_user_role_jurisdictions_role_id'), table_name='user_role_jurisdictions')
    op.drop_index(op.f('ix_user_role_jurisdictions_jurisdiction_id'), table_name='user_role_jurisdictions')
    op.drop_index(op.f('ix_user_role_jurisdictions_id'), table_name='user_role_jurisdictions')
    op.drop_table('user_role_jurisdictions')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_index(op.f('ix_users_mobile_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_emp_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_jurisdictions_type'), table_name='jurisdictions')
    op.drop_index(op.f('ix_jurisdictions_parent_id'), table_name='jurisdictions')
    op.drop_index(op.f('ix_jurisdictions_name'), table_name='jurisdictions')
    op.drop_index(op.f('ix_jurisdictions_id'), table_name='jurisdictions')
    op.drop_index(op.f('ix_jurisdictions_code'), table_name='jurisdictions')
    op.drop_table('jurisdictions')
    # ### end Alembic commands ###
